ALTER TABLE watchly.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchly.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchly.user_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchly.lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchly.list_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchly.profile_featured_media ENABLE ROW LEVEL SECURITY;
